Update client to use go modules
HotelsDotCom/flyte-client pull request #10
Opened 2019-09-25 14:15 UTC by TheColonelK

2019-09-25 16:25 UTC, ukjasonwright requested changes
All looks good apart from the travis.yml file - it has dep references

2019-09-26 08:56 UTC, isaacasensio commented
and please don't forget to remove Gopkg files too.
Thanks!

2019-09-26 08:57 UTC, isaacasensio requested changes
and please don't forget to remove Gopkg files too.
Thanks!

2019-09-26 12:42 UTC, isaacasensio approved these changes

2019-09-26 12:52 UTC, ukjasonwright approved these changes

2019-10-18 09:34 UTC, merged